### ISSUE TITLE
Fee recipient change not persisted

### ISSUE THREAD

**Issue by heeckhau** [prysmaticlabs/prysm#11322]
# 🐞 Bug Report

### Description

When I change the fee recipient of one or more specific validators with the KeyManager API, the changes are applied at first, but after a restart they are reset to the default.

I see the same behaviour when I use the Web UI:
* After configuring the fee recipient:
<img width="615" alt="Screenshot 2022-08-26 at 10 27 52" src="https://user-images.githubusercontent.com/735288/186864725-4a57eb5c-f12c-48a0-b0c9-b2577c43d0f2.png">
* After a restart (reset to the default address (`--suggested-fee-recipient`)
<img width="615" alt="Screenshot 2022-08-26 at 10 32 23" src="https://user-images.githubusercontent.com/735288/186864747-7b56e291-73a1-4193-80b6-28908c3b65ac.png">

## 🔬 Minimal Reproduction

1. Open the web UI.
2. Change the fee recipient of one of your validators (Actions: "Edit Fee recipient")
3. Restart the validator
4. The fee recipient is reset to the default

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Docker/Linux
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v3.0.0
  </code>
</pre>

**Anything else relevant ?**
I noticed my `wallet-dir` contains two `validator.db` files: one in the main folder and one in the `direct` folder. When I change the fee recipient address, the `direct/validator.db` changes, the other does not.
```
./auth-token
./validator.db
./direct
./direct/accounts
./direct/accounts/all-accounts.keystore.json
./direct/validator.db
```

**Comment by james-prysm** [comment]
Hi Heeku,  thanks for reporting this and reminding me to add a note on our documents. you are correct currently we don't have the feature to support persistence after restart via updates from the webUI. We can keep this issue open in the meantime to track this feature as I begin work on this.

to get around this I recommend using the --proposer-settings-file providing a config of the updated values, if you use this file it will persist on update. you can read more about this flag [ here ](https://docs.prylabs.network/docs/execution-node/fee-recipient)

in terms of the separate validator.db I believe the correct one is the one in the direct folder and not the one outside of the direct folder as you are using locally imported keys.

**Comment by heeckhau** [comment]
Hi James, thanks for the info.

That is unfortunate for my use case. I am developing a UI for Avado, that works with both Prysm and Teku. It is based on the KeyManager API, so I can avoid as much Prysm/Teku-specific code as possible.
I'll work around this for now, and mark it as a future simplification.

Does the persistence limitation also apply to importing keys with the Keymanager API?

**Comment by james-prysm** [comment]
This limitation wouldn't apply to importing keys as that gets saved to the Prysm wallet.

**Comment by james-prysm** [comment]
I merged a fix to develop, if anyone wants to try it out and provide any feedback here. the persistence happens at the start of each epoch.

**Comment by james-prysm** [comment]
still broken adding more fixes

**Comment by jwhelan72** [comment]
Still broken as of v3.1.2.  Quite frustrating actually when different batches of validators have different suggested fee recipient settings.  Can totally break privacy and general sanitization settings.

Can we save this to a file please instead of simply running in memory?

**Comment by heeckhau** [comment]
@jwhelan72 The workaround is to use a proposer settings file: https://docs.prylabs.network/docs/execution-node/fee-recipient

**Comment by james-prysm** [comment]
@jwhelan72 the setting is scheduled every epoch so it does try to persist after setting + the 1 epoch. could you let me know what happened in your case?

**Comment by james-prysm** [comment]
Tested persistence after 1 epoch. should persist as long as a validator flag is not provided( that would override the api result when restarting the validator). closing issue again , can reopen if needed.
