### ISSUE TITLE
Unable to retrieve proof-of-stake genesis block data

### ISSUE THREAD

**Issue by Fueav** [prysmaticlabs/prysm#12497]
# 🐞 Bug Report

### Description
I'm building my devnet creation node to block normally, and other nodes have encountered problems when joining.

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error

<pre>
<img width="2269" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/3031473f-649f-4dab-b206-40a733ecfcee">

[root@1-centos ~]# curl http://localhost:3500/eth/v1/node/syncing | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   106  100   106    0     0   103k      0 --:--:-- --:--:-- --:--:--  103k
{
  "data": {
    "head_slot": "612",
    "sync_distance": "0",
    "is_syncing": false,
    "is_optimistic": true,
    "el_offline": true
  }
}

connectionErrors":[]}[root@1-centos ~]# curl http://localhost:3500/eth/v1alpha1/node/eth1/connections |jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   258  100   258    0     0  86000      0 --:--:-- --:--:-- --:--:-- 86000
{
  "currentAddress": "http://127.0.0.1:8551",
  "currentConnectionError": "retryExecutionClientConnection: HeaderByHash, hash=0x9c1fb1381fbf30135583b2f618c80cb1076b91ea173acf5f2fbf4e976420a4ef: not found",
  "addresses": [
    "http://127.0.0.1:8551"
  ],
  "connectionErrors": []
}
<code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
CentOS Linux release 8.5.2111
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
prysm v4.0.5
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by aaroua5** [comment]
I have the same issue

**Comment by nisdas** [comment]
@Fueav @aaroua5 
https://github.com/OffchainLabs/eth-pos-devnet/tree/a293e5c52ec63a4e18fc691ee3013a9fb18e8694

You can try our latest devnet instructions, this should fix this issue

**Comment by Fueav** [comment]
@nisdas I updated the beacon-chain startup command, but the problem was not solved.
my genesis node Normal block production，But after I added the second node
<img width="2267" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/6507a020-3387-4b03-b353-f8c3c362ed20">
seconde node beacon-chain log:
<img width="2277" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/0158d6b4-145e-45a3-9ebd-8c34ef11f272">
and his status
<img width="1576" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/bce64199-d0d7-4ba6-a76e-e1e837d3cef0">
<img width="906" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/21611ef0-0457-449c-b6a1-dd1bea08317f">
seconde node validator log :
<img width="2283" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/fa984771-4a59-4bdf-904c-587e4c00ea2b">
This appears to be because the beacon-chain node is not ready, and the beacon-chain thinks there is a problem with its connection to the execution node, making it unable to query for the genesis block.

As for the error logs of the genesis node, it seems to be a network issue that caused a delay in the synchronization of p2p information. However, I am sure that I have synchronized the time according to timedatectl.
<img width="598" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/ea846aaf-53d1-4f96-9144-b4ba7a188188">

**Comment by nisdas** [comment]
@Fueav It means your node is syncing, you will have to wait for it to be fully synced

**Comment by Fueav** [comment]
I don't think so, because I noticed that the sync_distance is 0.

**Comment by nisdas** [comment]
No, the logs in indicate your execution client is still syncing. So wait for that to finish syncing first

**Comment by Fueav** [comment]
@nisdas In fact, I once maintained this state for more than 12 hours. The situation did not improve and there were not many blocks in the devnet, which quickly caught up with the footsteps of the genesis node.

**Comment by nisdas** [comment]
Maybe you should look at your execution logs in that case @Fueav , it would indicate what the issue is

**Comment by Fueav** [comment]
@nisdas geth seems to be synchronizing blocks through fork choice, the only thing worth noting is this warning log.
<img width="1698" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/55bb5157-cc1b-4813-bf00-046f10805c5c">

**Comment by nisdas** [comment]
Looks like it has not peers @Fueav , it maybe better to do a full sync. `--syncmode=full`

**Comment by Fueav** [comment]
it's my geth.service
<img width="2276" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/34ef5811-f257-4bda-98c9-0144a1efae75">
Beacon-chain p2p connection is configured and working properly.
<img width="2269" alt="image" src="https://github.com/prysmaticlabs/prysm/assets/104292973/bf12e866-6a8f-4796-bc62-28387640b5d9">
Does that mean geth also needs to configure the boot node?

**Comment by Fueav** [comment]
@nisdas geth is already --syncmode=full

**Comment by nisdas** [comment]
You can give that a try, our devnet instructions are only for 1 node currently. If you need to add multiple nodes, then you will have to configure a geth/execution bootnode.

**Comment by Fueav** [comment]
I tried, but it didn't work.v4.0.3 running normally, and I'm ready to revert back to this version.

**Comment by icemagno** [comment]
Any progress?
I've seen Geth is having many trouble to work with multinode primate blockchain...

Many... many issues mainly involving sync

**Comment by wangyufsn** [comment]
@icemagno I encountered the same error. How did you resolve it?

**Comment by Gopal-Gurram** [comment]
@Fueav  , @lyfsn , @nisdas 
 did you resolve the 
 Forkchoice requested sync to new head    number=98 hash=748935..d423c8 finalized=75 issue ?
 I am facing that while connecting the second node from the localhost and my first node is in droplet and i used the bootnode from geth and bootstrap-node and peer from the beacon node ?

**Comment by netoneko** [comment]
@Gopal-Gurram same issue, trying to add another node to this proof of stake devnet setup and if fails to sync. Did you resolve your issue?

**Comment by Gopal-Gurram** [comment]
no @netoneko

**Comment by icemagno** [comment]
@lyfsn  I've started to use Hyperledger Besu.

**Comment by prestonvanloon** [comment]
Closing old issues. This seems like a devnet setup issue rather than a Prysm issue. Please file again with reproduction steps if this is still an issue.

**Comment by Chidiebere95** [comment]
<img width="804" alt="Image" src="https://github.com/user-attachments/assets/c6c96103-33a4-4903-8fde-61349afe84cf" />

I have the same issue. My sync_distance says 0, yet the geth wont let me sign transactions.
