### ISSUE TITLE
prysm 4.2.0 shuts down with an error "SIGILL: illegal instruction"

### ISSUE THREAD

**Issue by Jony321** [prysmaticlabs/prysm#13485]
### Describe the bug

After the hard fork "Cancun" described in the [new version](https://github.com/ethereum/go-ethereum/releases/tag/v1.13.10) of go-etherium, stopped synchronizing in the Goerli network.
Synchronization stopped due to the prism container being turned off.

### Has this worked before in a previous version?

```text
Everything worked on versions:
geth - v1.13.9
prysm - v4.1.1
```

### 🔬 Minimal Reproduction

<details closed> 
<summary> 1. I'm started container like below: </summary>

```
  prysm:
    container_name: ${PRYSM_CONTAINER_NAME}
    image: ${PRYSM_IMAGE}
    depends_on:
      - geth
    volumes: 
      - ${HOST_DATADIR}:${DATADIR}
    ports:
      - "${PRYSM_PEER_LISTEN_ADDR}:${PRYSM_PEER_LISTEN_PORT}:13000"
      - "${PRYSM_NODE_LISTEN_ADDR}:${PRYSM_NODE_LISTEN_PORT}:12000/udp"
    stop_grace_period: 1m30s
    command: 
      --datadir=${DATADIR}
      --jwt-secret=${JWTSECRET_PATH}
      --rpc-host=0.0.0.0
      --grpc-gateway-host=0.0.0.0
      --monitoring-host=0.0.0.0
      --execution-endpoint=${PRYSM_EXECUTION_ENDPOINT}
      --accept-terms-of-use
      --${BLOCKCHAIN_NET}
      ${PRYSM_ADDITIONAL_COMMAND}
```

</details>

<details closed>
<summary> 2. Prism works for 5-10 minutes with logs like: </summary>

```                                                                                 
time="2024-01-18 14:27:02" level=info msg="Node started p2p server" multiAddr="/ip4/172.18.0.3/tcp/13000/p2p/[secret_string???]" prefix=p2p                                                                                                                  
time="2024-01-18 14:27:07" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0          
time="2024-01-18 14:27:12" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0          
time="2024-01-18 14:27:12" level=info msg="Connected to new endpoint: /***" prefix=execution                                                    
time="2024-01-18 14:27:17" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2024-01-18 14:27:26" level=info msg="Processing block batch of size 22 starting from  0xf2c2e73c... 7413698/7423337 - estimated time remai
ning 2h26m2s" blocksPerSecond=1.1 peers=4 prefix=initial-sync
time="2024-01-18 14:28:02" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
time="2024-01-18 14:28:02" level=info msg="Peer summary" activePeers=2 inbound=0 outbound=1 prefix=p2p
time="2024-01-18 14:28:07" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=2
time="2024-01-18 14:29:02" level=info msg="Peer summary" activePeers=15 inbound=0 outbound=15 prefix=p2p
time="2024-01-18 14:29:46" level=info msg="Processing block batch of size 42 starting from  0x60ab3457... 7413727/7423348 - estimated time remai
ning 1h16m21s" blocksPerSecond=2.1 peers=14 prefix=initial-sync
time="2024-01-18 14:30:02" level=info msg="Peer summary" activePeers=12 inbound=2 outbound=7 prefix=p2p
time="2024-01-18 14:30:05" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x8db647a21226 prefix=blockchain slot=7413
762
time="2024-01-18 14:30:05" level=info msg="Called new payload with optimistic block" payloadBlockHash=0xfebe087b7de5 prefix=blockchain slot=7413
763
```

</details>

3. I get an error and prism is disabled

### Error

```text
time="2024-01-18 14:30:05" level=info msg="Called new payload with optimistic block" payloadBlockHash=0xfebe087b7de5 prefix=blockchai[3508/7353]
763                                                                                                                                             
time="2024-01-18 14:30:05" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x9ccb3ba48b23 prefix=blockchain slot=7413
766                                                                                                                                             
time="2024-01-18 14:30:06" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x9e1658245657 prefix=blockchain slot=7413
769                                                                                                                                             
SIGILL: illegal instruction                                                                                                                     
PC=0x215949c m=5 sigcode=2
instruction bytes: 0xc5 0x7a 0x6f 0x2d 0xbc 0xe9 0xbb 0xfe 0xc5 0x7a 0x6f 0x15 0x24 0x9e 0xb9 0xfe
goroutine 29952 [running]:
github.com/prysmaticlabs/gohashtree._hash(0xc04704fc80, {0xc04704fc80, 0x2, 0x2}, 0x1)
        external/com_github_prysmaticlabs_gohashtree/hash_amd64.s:1061 +0x79dc fp=0xc04045b568 sp=0xc04045b1b8 pc=0x215949c
created by github.com/prysmaticlabs/prysm/v4/runtime.(*ServiceRegistry).StartAll in goroutine 1
        runtime/service_registry.go:46 +0xe7
goroutine 1 [chan receive, 3 minutes]:
runtime.gopark(...)
        GOROOT/src/runtime/proc.go:398
runtime.chanrecv(0xc000538900, 0x0, 0x1)
        GOROOT/src/runtime/chan.go:583 +0x5ae fp=0xc043e47840 sp=0xc043e47778 pc=0x1c978ce
runtime.chanrecv1(0xc0004ae6a8?, 0xc000000004?)
        GOROOT/src/runtime/chan.go:442 +0x12 fp=0xc043e47868 sp=0xc043e47840 pc=0x1c972f2
github.com/prysmaticlabs/prysm/v4/beacon-chain/node.(*BeaconNode).Start(0xc0004ae680)
        beacon-chain/node/node.go:375 +0x1a8 fp=0xc043e47a08 sp=0xc043e47868 pc=0x3258908
main.startNode(0x1c9fb25?, 0x18?)
        cmd/beacon-chain/main.go:305 +0x76a fp=0xc043e47b90 sp=0xc043e47a08 pc=0x326b5ca
main.main.func1(0xc000416160?)
```

### What version of Prysm are you running? (Which release)

4.2.0

### Anything else relevant (validator index / public key)?

I tried using other versions suggested in other issues:
1. [Comment](https://github.com/prysmaticlabs/prysm/issues/13478#issuecomment-1895509660) - Image `gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-fe431b`
2. [Comment](https://github.com/prysmaticlabs/prysm/issues/13483#issuecomment-1897991073) - version [v4.2.1-rc.0](https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.1-rc.0)

But I get the same errors.

I'm running a node on a virtual machine QEMU KVM with 4 threads of `Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz`

**Comment by potuz** [comment]
please can you post a little more on the execution environment? this is QEMU of x86_64 with host being  the same architecture? Did you run the same exact environment before?

**Comment by potuz** [comment]
Could you also check if QEMU's version has changed?

**Comment by Piradoxlanieve** [comment]
Hi @potuz sorry my english.

PRYSM 4.2.0
geth version 1.13.5-stable-916d6a44

It's been two days since my node stops validating, and I have to restart all the geth, prysm (beacon and validator) and mevboost services, since only if the beacon is restarted it doesn't work, I think it is not the same problem, but I have virtualized in proxmox in HOST mode

Beacon service
```

Jan 24 05:45:14 nodoeth prysm[251901]: time="2024-01-24 05:45:14" level=info msg="Synced new block" block=0x11c2ff54... epoch=258456 finalizedEpoch=258454 finalizedRoot=0x216a191e... prefix=blockchain slot=8270623
Jan 24 05:45:14 nodoeth prysm[251901]: time="2024-01-24 05:45:14" level=info msg="Finished applying state transition" attestations=121 payloadHash=0x0921d49290f5 prefix=blockchain slot=8270623 syncBitsCount=502 txCount=164 voluntaryExits=4
Jan 24 05:45:21 nodoeth prysm[251901]: time="2024-01-24 05:45:21" level=error msg="could not compute payload attributes" error="could not update next slot state cache: could not process slots: could not process epoch: could not process registry updates: could not get active validator count: could not interface with committee cache: context deadline exceeded" prefix=blockchain
Jan 24 05:45:24 nodoeth prysm[251901]: time="2024-01-24 05:45:24" level=error msg="Could not handle p2p pubsub" error="could not notify the engine of the new payload: timeout from http.Client: received an undefined execution engine error" prefix=sync topic="/eth2/bba4da96/beacon_block/ssz_snappy"
Jan 24 05:45:38 nodoeth systemd[1]: beacon-chain.service: A process of this unit has been killed by the OOM killer.
Jan 24 05:45:38 nodoeth systemd[1]: beacon-chain.service: Main process exited, code=killed, status=9/KILL
Jan 24 05:45:38 nodoeth systemd[1]: beacon-chain.service: Failed with result 'oom-kill'.
Jan 24 05:45:38 nodoeth systemd[1]: beacon-chain.service: Consumed 11h 15min 28.246s CPU time.
Jan 24 05:45:42 nodoeth systemd[1]: beacon-chain.service: Scheduled restart job, restart counter is at 1.
Jan 24 05:45:42 nodoeth systemd[1]: Stopped Prysm Consensus Layer Client service for Mainnet.
Jan 24 05:45:42 nodoeth systemd[1]: beacon-chain.service: Consumed 11h 15min 28.246s CPU time.
Jan 24 05:45:42 nodoeth systemd[1]: Started Prysm Consensus Layer Client service for Mainnet.
Jan 24 05:45:43 nodoeth prysm[289318]: Latest Prysm version is v4.2.0.
Jan 24 05:45:43 nodoeth prysm[289318]: Beacon chain is up to date.
Jan 24 05:45:43 nodoeth prysm[289318]: Verifying binary integrity.
Jan 24 05:45:46 nodoeth prysm[289332]: beacon-chain-v4.2.0-linux-amd64: OK
Jan 24 05:45:47 nodoeth prysm[289334]: gpg: Signature made Thu Jan 11 04:04:52 2024 CET
Jan 24 05:45:47 nodoeth prysm[289334]: gpg:                using RSA key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E
Jan 24 05:45:47 nodoeth prysm[289334]: gpg: Good signature from "Preston Van Loon <preston@pvl.dev>" [unknown]
Jan 24 05:45:47 nodoeth prysm[289334]: gpg:                 aka "Preston Van Loon <preston@prysmaticlabs.com>" [unknown]
Jan 24 05:45:47 nodoeth prysm[289334]: gpg:                 aka "Preston Van Loon <preston90@gmail.com>" [unknown]
Jan 24 05:45:47 nodoeth prysm[289334]: gpg:                 aka "Preston Van Loon (0xf71E9C766Cdf169eDFbE2749490943C1DC6b8A55) <preston@machinepowered.com>" [unknown]
Jan 24 05:45:47 nodoeth prysm[289334]: gpg: WARNING: This key is not certified with a trusted signature!
Jan 24 05:45:47 nodoeth prysm[289334]: gpg:          There is no indication that the signature belongs to the owner.
Jan 24 05:45:47 nodoeth prysm[289334]: Primary key fingerprint: 0AE0 051D 647B A3C1 A917  AF40 72E3 3E4D F1A5 036E
Jan 24 05:45:47 nodoeth prysm[289318]: Verified /home/consensus/dist/beacon-chain-v4.2.0-linux-amd64 has been signed by Prysmatic Labs.
Jan 24 05:45:47 nodoeth prysm[289318]: Starting Prysm beacon-chain --mainnet --datadir=/home/nodo/nodoeth2/snap --enable-debug-rpc-endpoints --grpc-max-msg-size=65568081 --checkpoint-sync-url=https://beaconstate.info --genesis-beacon-api-url=https://beaconstate.info --execution-endpoint=http://localhost:8551 --jwt-secret=/home/consensus/secrets/jwtsecret --http-mev-relay=http://127.0.0.1:18550 --p2p-max-peers 100 --accept-terms-of-use=true --suggested-fee-recipient=0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Jan 24 05:45:47 nodoeth prysm[289318]: time="2024-01-24 05:45:47" level=info msg="Finished reading JWT secret from /home/consensus/secrets/jwtsecret"
Jan 24 05:45:47 nodoeth prysm[289318]: time="2024-01-24 05:45:47" level=warning msg="Running on Ethereum Mainnet" prefix=flags
Jan 24 05:45:47 nodoeth prysm[289318]: time="2024-01-24 05:45:47" level=info msg="Default fee recipient is set to 0x10A86245bF4cd0a551c04A2aC7C5A398B66503f0, recipient may be overwritten from validator client and persist in db. Default fee recipient will be used as a fall back" prefix=node
Jan 24 05:45:47 nodoeth prysm[289318]: time="2024-01-24 05:45:47" level=info msg="Checking DB" database-path="/home/nodo/nodoeth2/snap/beaconchaindata" prefix=node
Jan 24 05:45:47 nodoeth prysm[289318]: time="2024-01-24 05:45:47" level=info msg="Opening Bolt DB at /home/nodo/nodoeth2/snap/beaconchaindata/beaconchain.db" prefix=db
Jan 24 05:45:51 nodoeth prysm[289318]: time="2024-01-24 05:45:51" level=warning msg="database contains genesis with htr=0x7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b, ignoring remote genesis state parameter" prefix=genesis
Jan 24 05:45:51 nodoeth prysm[289318]: time="2024-01-24 05:45:51" level=warning msg="origin checkpoint root 0x48ecd058b125fa63df356670ec577e123db8c85ea5a076e1d1cd82f2902741ed found in db, ignoring checkpoint sync flags"
Jan 24 05:45:51 nodoeth prysm[289318]: time="2024-01-24 05:45:51" level=info msg="Deposit contract: 0x00000000219ab540356cbb839cbe05303d7705fa" prefix=node
Jan 24 05:46:55 nodoeth prysm[289318]: time="2024-01-24 05:46:55" level=info msg="Running node with peer id of 16Uiu2HAm2iG8quSZyEmJYUQPqsVp2DFsLHeGEiB5ZZrZcbuadCPL " prefix=p2p
Jan 24 05:48:16 nodoeth prysm[289318]: time="2024-01-24 05:48:16" level=info msg="Builder has been configured" endpoint="http://127.0.0.1:18550"
```
validator
```
Jan 24 05:45:03 nodoeth prysm[251888]: time="2024-01-24 05:45:03" level=info msg="Previous epoch voting summary" correctlyVotedHead=true correctlyVotedSource=true correctlyVotedTarget=true epoch=258455 inactivityScore=0 newBalance=32.000613906 oldBalance=32.000603843 percentChange="0.00003%" percentChangeSinceStart="-0.04306%" prefix=validator pubKey=0x8da251b37c20 startBalance=32.014400791
Jan 24 05:45:03 nodoeth prysm[251888]: time="2024-01-24 05:45:03" level=info msg="Previous epoch aggregated voting summary" attestationInclusionPct="100%" averageInactivityScore=0 correctlyVotedHeadPct="100%" correctlyVotedSourcePct="100%" correctlyVotedTargetPct="100%" epoch=258455 prefix=validator
Jan 24 05:45:03 nodoeth prysm[251888]: time="2024-01-24 05:45:03" level=info msg="Vote summary since launch" attestationsInclusionPct="100%" correctlyVotedHeadPct="95%" correctlyVotedSourcePct="100%" correctlyVotedTargetPct="100%" numberOfEpochs=366 pctChangeCombinedBalance="-0.04310%" prefix=validator
Jan 24 05:45:39 nodoeth prysm[251888]: time="2024-01-24 05:45:38" level=info msg="Attestation schedule" attesterDutiesAtSlot=1 prefix=validator pubKeys=[0x8da251b37c20] slot=8270653 slotInEpoch=29 timeTillDuty=5m21s totalAttestersInEpoch=1
Jan 24 05:45:39 nodoeth prysm[251888]: time="2024-01-24 05:45:39" level=error msg="Could not receive slots from beacon node, could not connect" error="rpc error: code = Unavailable desc = error reading from server: EOF" prefix=validator
Jan 24 05:45:39 nodoeth prysm[251888]: time="2024-01-24 05:45:39" level=warning msg="slots stream interrupted" error="rpc error: code = Unavailable desc = error reading from server: EOF: could not connect" prefix=validator
Jan 24 05:45:43 nodoeth prysm[251888]: time="2024-01-24 05:45:43" level=warning msg="Failed to update proposer settings" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator slot=8270624
Jan 24 05:45:43 nodoeth prysm[251888]: time="2024-01-24 05:45:43" level=error msg="Failed to subscribe to subnets" error="could not check if a validator is an aggregator: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Jan 24 05:45:43 nodoeth prysm[251888]: time="2024-01-24 05:45:43" level=error msg="Failed to retrieve slots stream, could not connect" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Jan 24 05:45:43 nodoeth prysm[251888]: time="2024-01-24 05:45:43" level=warning msg="slots stream interrupted" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused": could not connect" prefix=validator
Jan 24 05:45:47 nodoeth prysm[251888]: time="2024-01-24 05:45:47" level=error msg="Failed to retrieve slots stream, could not connect" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Jan 24 05:45:47 nodoeth prysm[251888]: time="2024-01-24 05:45:47" level=warning msg="slots stream interrupted" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused": could not connect" prefix=validator
Jan 24 05:45:51 nodoeth prysm[251888]: time="2024-01-24 05:45:51" level=error msg="Failed to retrieve slots stream, could not connect" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused"" prefix=validator
Jan 24 05:45:51 nodoeth prysm[251888]: time="2024-01-24 05:45:51" level=warning msg="slots stream interrupted" error="rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4000: connect: connection refused": could not connect" prefix=validator
```

GEth
```
Jan 24 05:44:25 nodoeth geth[251960]: INFO [01-24|05:44:25.254] Imported new potential chain segment     number=19,074,200 hash=ebd962..3d3a1c blocks=1  txs=157  mgas=18.911  elapsed=323.429ms   mgasps=58.469  snapdiffs=5.33MiB triediffs=193.32MiB triedirty=38.00MiB
Jan 24 05:44:25 nodoeth geth[251960]: INFO [01-24|05:44:25.467] Chain head was updated                   number=19,074,200 hash=ebd962..3d3a1c root=a67fac..deb1f4 elapsed=6.554222ms
Jan 24 05:44:36 nodoeth geth[251960]: INFO [01-24|05:44:36.867] Imported new potential chain segment     number=19,074,201 hash=28a2d4..c11273 blocks=1  txs=124  mgas=11.612  elapsed=152.931ms   mgasps=75.927  snapdiffs=5.36MiB triediffs=193.40MiB triedirty=38.24MiB
Jan 24 05:44:37 nodoeth geth[251960]: INFO [01-24|05:44:37.557] Chain head was updated                   number=19,074,201 hash=28a2d4..c11273 root=641e45..ba536b elapsed=5.249165ms
Jan 24 05:44:49 nodoeth geth[251960]: INFO [01-24|05:44:49.328] Imported new potential chain segment     number=19,074,202 hash=630668..a36dde blocks=1  txs=97   mgas=12.138  elapsed=146.699ms   mgasps=82.740  snapdiffs=5.39MiB triediffs=193.14MiB triedirty=38.58MiB
Jan 24 05:44:49 nodoeth geth[251960]: INFO [01-24|05:44:49.511] Chain head was updated                   number=19,074,202 hash=630668..a36dde root=5f6a1d..35e105 elapsed=5.42117ms
Jan 24 05:45:04 nodoeth geth[251960]: INFO [01-24|05:45:04.130] Imported new potential chain segment     number=19,074,203 hash=0921d4..e4df25 blocks=1  txs=164  mgas=15.195  elapsed=1.664s      mgasps=9.129   snapdiffs=5.43MiB triediffs=192.93MiB triedirty=39.10MiB
Jan 24 05:45:14 nodoeth geth[251960]: INFO [01-24|05:45:14.925] Chain head was updated                   number=19,074,203 hash=0921d4..e4df25 root=9167f7..73e071 elapsed=24.236201ms
Jan 24 05:45:46 nodoeth geth[251960]: INFO [01-24|05:45:46.469] Imported new potential chain segment     number=19,074,204 hash=1aab1f..01e62f blocks=1  txs=170  mgas=24.363  elapsed=30.593s     mgasps=0.796   snapdiffs=5.49MiB triediffs=194.24MiB triedirty=39.59MiB
Jan 24 05:47:15 nodoeth geth[251960]: WARN [01-24|05:47:15.986] Beacon client online, but no consensus updates received in a while. Please fix your beacon client to follow the chain!
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.558] Ignoring already known beacon payload    number=19,074,110 hash=20cc19..84c354 age=23m27s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.578] Ignoring already known beacon payload    number=19,074,111 hash=81a7b2..16aab1 age=23m15s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.586] Ignoring already known beacon payload    number=19,074,112 hash=061760..a066f7 age=23m3s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.604] Ignoring already known beacon payload    number=19,074,113 hash=b3b1ce..6abdd8 age=22m51s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.619] Ignoring already known beacon payload    number=19,074,114 hash=0ebce7..c4a21d age=22m39s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.645] Ignoring already known beacon payload    number=19,074,115 hash=be5816..f60c9b age=22m27s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.653] Ignoring already known beacon payload    number=19,074,116 hash=12062c..bea2a5 age=22m15s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.660] Ignoring already known beacon payload    number=19,074,117 hash=8f36af..4ab9ac age=22m3s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.672] Ignoring already known beacon payload    number=19,074,118 hash=81c5cd..639699 age=21m51s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.705] Ignoring already known beacon payload    number=19,074,119 hash=533da5..16f563 age=21m39s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.714] Ignoring already known beacon payload    number=19,074,120 hash=a475e3..0f8b9f age=21m27s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.730] Ignoring already known beacon payload    number=19,074,121 hash=240efb..26ee89 age=21m15s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.736] Ignoring already known beacon payload    number=19,074,122 hash=35b5c5..ea1146 age=21m3s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.749] Ignoring already known beacon payload    number=19,074,123 hash=0be384..238afb age=20m51s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.756] Ignoring already known beacon payload    number=19,074,124 hash=774ee5..08e766 age=20m39s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.781] Ignoring already known beacon payload    number=19,074,125 hash=83b9b6..009eb8 age=20m27s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.800] Ignoring already known beacon payload    number=19,074,126 hash=867a6c..53ed23 age=20m15s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.806] Ignoring already known beacon payload    number=19,074,127 hash=4e4fe6..96c9b6 age=20m3s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.821] Ignoring already known beacon payload    number=19,074,128 hash=173330..e5ebba age=19m51s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.825] Ignoring already known beacon payload    number=19,074,129 hash=a14d06..a3700f age=19m39s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.845] Ignoring already known beacon payload    number=19,074,130 hash=83e07f..7993d7 age=19m27s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.909] Ignoring already known beacon payload    number=19,074,131 hash=ef6d13..28cc42 age=19m15s
Jan 24 05:49:38 nodoeth geth[251960]: WARN [01-24|05:49:38.930] Ignoring already known beacon payload    number=19,074,132 hash=850ff1..d06a11 age=18m51s
Jan 24 05:49:39 nodoeth geth[251960]: WARN [01-24|05:49:39.048] Ignoring already known beacon payload    number=19,074,133 hash=0fd79f..fb29be age=18m40s
Jan 24 05:49:39 nodoeth geth[251960]: WARN [01-24|05:49:39.073] Ignoring already known beacon payload    number=19,074,134 hash=4413ca..b2f284 age=18m28s
Jan 24 05:49:39 nodoeth geth[251960]: WARN [01-24|05:49:39.102] Ignoring already known beacon payload    number=19,074,135 hash=c9b4c9..d75d1f age=18m16s
Jan 24 05:49:39 nodoeth geth[251960]: WARN [01-24|05:49:39.119] Ignoring already known beacon payload    number=19,074,136 hash=9972f8..dbaef4 age=18m4s
Jan 24 05:49:39 nodoeth geth[251960]: WARN [01-24|05:49:39.128] Ignoring already known beacon payload    number=19,074,137 hash=f860e6..ae7ed1 age=17m52s
Jan 24 05:49:39 nodoeth geth[251960]: WARN [01-24|05:49:39.181] Ignoring already known beacon payload    number=19,074,138 hash=cb6c51..e1ef45 age=17m40s
Jan 24 05:49:39 nodoeth geth[251960]: WARN [01-24|05:49:39.191] Ignoring already known beacon payload    number=19,074,139 hash=711e34..14dbfb age=17m28s
Jan 24 05:49:39 nodoeth geth[251960]: INFO [01-24|05:49:39.245] Ignoring beacon update to old head       number=19,074,139 hash=711e34..14dbfb age=17m28s    have=19,074,203
```
Mevboost
```
Jan 24 05:32:23 nodoeth mev-boost[251883]: time="2024-01-24T05:32:23.382+01:00" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.042554 method=POST path=/eth/v1/builder/validators status=200 version=v1.6
Jan 24 05:32:25 nodoeth mev-boost[251883]: time="2024-01-24T05:32:25.346+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.114474 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:33:25 nodoeth mev-boost[251883]: time="2024-01-24T05:33:25.365+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.134030 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:34:25 nodoeth mev-boost[251883]: time="2024-01-24T05:34:25.439+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.207557 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:35:25 nodoeth mev-boost[251883]: time="2024-01-24T05:35:25.599+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.367573 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:36:25 nodoeth mev-boost[251883]: time="2024-01-24T05:36:25.573+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.342214 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:37:25 nodoeth mev-boost[251883]: time="2024-01-24T05:37:25.368+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.137072 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:38:25 nodoeth mev-boost[251883]: time="2024-01-24T05:38:25.369+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.138567 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:38:47 nodoeth mev-boost[251883]: time="2024-01-24T05:38:47.334+01:00" level=info msg="http: POST /eth/v1/builder/validators 200" duration=0.035859 method=POST path=/eth/v1/builder/validators status=200 version=v1.6
Jan 24 05:39:25 nodoeth mev-boost[251883]: time="2024-01-24T05:39:25.353+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.120536 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:40:25 nodoeth mev-boost[251883]: time="2024-01-24T05:40:25.366+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.134066 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:41:25 nodoeth mev-boost[251883]: time="2024-01-24T05:41:25.368+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.136880 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:42:25 nodoeth mev-boost[251883]: time="2024-01-24T05:42:25.404+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.170579 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:43:25 nodoeth mev-boost[251883]: time="2024-01-24T05:43:25.374+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.142749 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:44:25 nodoeth mev-boost[251883]: time="2024-01-24T05:44:25.381+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.150418 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:48:16 nodoeth mev-boost[251883]: time="2024-01-24T05:48:16.676+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.303827 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:49:16 nodoeth mev-boost[251883]: time="2024-01-24T05:49:16.873+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.171822 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:50:17 nodoeth mev-boost[251883]: time="2024-01-24T05:50:17.022+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.235340 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:56:57 nodoeth mev-boost[251883]: time="2024-01-24T05:56:57.82+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.300906 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 05:59:10 nodoeth mev-boost[251883]: time="2024-01-24T05:59:10.235+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.298674 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:01:34 nodoeth mev-boost[251883]: time="2024-01-24T06:01:34.885+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.290732 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:02:35 nodoeth mev-boost[251883]: time="2024-01-24T06:02:35.139+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.237134 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:04:26 nodoeth mev-boost[251883]: time="2024-01-24T06:04:26.157+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.206509 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:05:27 nodoeth mev-boost[251883]: time="2024-01-24T06:05:27.976+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.434306 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:12:20 nodoeth mev-boost[251883]: time="2024-01-24T06:12:20.988+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.334191 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:14:01 nodoeth mev-boost[251883]: time="2024-01-24T06:14:01.58+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.316530 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:17:40 nodoeth mev-boost[251883]: time="2024-01-24T06:17:40.541+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.209065 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:18:41 nodoeth mev-boost[251883]: time="2024-01-24T06:18:41.13+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.301737 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:21:41 nodoeth mev-boost[251883]: time="2024-01-24T06:21:41.776+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.400539 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:29:28 nodoeth mev-boost[251883]: time="2024-01-24T06:29:28.462+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.337935 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:30:28 nodoeth mev-boost[251883]: time="2024-01-24T06:30:28.745+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.240587 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:33:38 nodoeth mev-boost[251883]: time="2024-01-24T06:33:38.115+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.282547 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:34:38 nodoeth mev-boost[251883]: time="2024-01-24T06:34:38.42+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.239540 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:37:08 nodoeth mev-boost[251883]: time="2024-01-24T06:37:08.925+01:00" level=error msg="relay status error - request failed" error="Get \"https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/status\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" url="https://bloxroute.max-profit.blxrbdn.com/eth/v1/builder/status" version=v1.6
Jan 24 06:37:08 nodoeth mev-boost[251883]: time="2024-01-24T06:37:08.931+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=1.160042 method=GET path=/eth/v1/builder/status status=200 version=v1.6
Jan 24 06:39:54 nodoeth mev-boost[251883]: time="2024-01-24T06:39:54.966+01:00" level=info msg="http: GET /eth/v1/builder/status 200" duration=0.285681 method=GET path=/eth/v1/builder/status status=200 version=v1.6
```

**Comment by Jony321** [comment]
> please can you post a little more on the execution environment? this is QEMU of x86_64 with host being the same architecture? Did you run the same exact environment before?

Yes, the host and VM have the same architecture - x86_64 both on Ubuntu 20.04.4 LTS.
The host and VM have been operating without changes in configuration for more than a year, prysm runs in the container into VM and changes occur only in it.

> Could you also check if QEMU's version has changed?
```
$ qemu-system-x86_64 --version
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.28)
```
According to the logs, QEMU packages updated 2024-01-09 to the current version.

But I don't think the problem is with the update, because. The problems started right at the moment of the hard fork
> Deneb Goerli Support
>This release adds in full support for the upcoming deneb hard fork on goerli next week on January 17th.

https://github.com/prysmaticlabs/prysm/releases/tag/v4.2.0

**Comment by Jony321** [comment]
@potuz 
And one more thing, the problem is only in the geth test network (Goerli), 2 mainnet nodes work well.

**Comment by potuz** [comment]
@Jony321 can you tell me the exact CPU of the host?

**Comment by Jony321** [comment]
@potuz 
Sure.
Host's processor:
```
$ cat /proc/cpuinfo | grep "model name" | sort | uniq
model name      : Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz
```

I wrote about this in the ticket, at the very bottom.
Or did I misunderstand your question?

**Comment by potuz** [comment]
@Jony321 thanks for the report, this happens in Deneb on unsuported CPUs, I'm a bit surprised the Xeon would fail, but 

1. This issue itself is fixed in the gohashtree linked PR
2. If you could send me the output of `cat /proc/cpuinfo | grep flags` on that CPU that'd be awesome.

**Comment by Jony321** [comment]
@potuz 
Nice.
1. Ok, I'll try ti use this.
2. 
```
$ cat /proc/cpuinfo | grep flags | sort | uniq
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities
```

**Comment by Jony321** [comment]
@potuz 
Hello!
Unfortunately, the new version of prism (4.2.1) did not solve the problem. After a few minutes, the prism terminates with the same error as before.
```
instruction bytes: 0xc5 0x7a 0x6f 0x2d 0xbc 0x5d 0xbb 0xfe 0xc5 0x7a 0x6f 0x15 0xd4 0xf 0xb9 0xfe
goroutine 4712 [running]:
github.com/prysmaticlabs/gohashtree._hash(0xc010671d80, {0xc010671d80, 0x2, 0x2}, 0x1)
        external/com_github_prysmaticlabs_gohashtree/hash_amd64.s:1061 +0x79dc fp=0xc027d35568 sp=0xc027d351b8 p
c=0x216809c
created by github.com/prysmaticlabs/prysm/v4/runtime.(*ServiceRegistry).StartAll in goroutine 1
        runtime/service_registry.go:46 +0xe7
goroutine 1 [chan receive, 1 minutes]:
runtime.gopark(...)

[OMMITED]
```

Please open my problem again, I'm don't know how resolve this problem.

I'm not the only one who has a similar problem; for example, the ticket contains a similar error - #13567

**Comment by ThomasBlock** [comment]
@Jony321 i had the same problem on 4.2.1. goerli inside a vm was crashing when conencting to the first network node.
but 4.2.2 solved my problem
