### ISSUE TITLE
v5.3.2 fails to find peers

### ISSUE THREAD

**Issue by abbaahmad** [prysmaticlabs/prysm#15100]
### Describe the bug

Upgrading prysm-beacon to 5.3.1on Ubuntu 22.04 leads the beacon to find peers. 
```
Mar 27 16:07:58  beacon-chain[2540402]: time="2025-03-27 16:07:58" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:03  beacon-chain[2540402]: time="2025-03-27 16:08:03" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:08  beacon-chain[2540402]: time="2025-03-27 16:08:08" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:13  beacon-chain[2540402]: time="2025-03-27 16:08:13" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:18  beacon-chain[2540402]: time="2025-03-27 16:08:18" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:23  beacon-chain[2540402]: time="2025-03-27 16:08:23" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:28  beacon-chain[2540402]: time="2025-03-27 16:08:28" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:33  beacon-chain[2540402]: time="2025-03-27 16:08:33" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:38  beacon-chain[2540402]: time="2025-03-27 16:08:38" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:43  beacon-chain[2540402]: time="2025-03-27 16:08:43" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
Mar 27 16:08:48  beacon-chain[2540402]: time="2025-03-27 16:08:48" level=info msg="Connected peers" inboundQUIC=0 inboundTCP=0 outboundQUIC=0 outboundTCP=0 prefix=p2p total=0
Mar 27 16:08:48  beacon-chain[2540402]: time="2025-03-27 16:08:48" level=info msg="Waiting for enough suitable peers before syncing" prefix=initial-sync required=3 suitable=0
```
`curl http://localhost:8080/p2p` returns the following:
```
bootnode=[enr:-Ku4QDZ_rCowZFsozeWr60WwLgOfHzv1Fz2cuMvJqN5iJzLxKtVjoIURY42X_YTokMi3IGstW5v32uSYZyGUXj9Q_IECh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCo_ujukAAAaf__________gmlkgnY0gmlwhIpEe5iJc2VjcDI1NmsxoQNHTpFdaNSCEWiN_QqT396nb0PzcUpLe3OVtLph-AciBYN1ZHCCIy0 enr:-Ku4QHRyRwEPT7s0XLYzJ_EeeWvZTXBQb4UCGy1F_3m-YtCNTtDlGsCMr4UTgo4uR89pv11uM-xq4w6GKfKhqU31hTgCh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCo_ujukAAAaf__________gmlkgnY0gmlwhIrFM7WJc2VjcDI1NmsxoQI4diTwChN3zAAkarf7smOHCdFb1q3DSwdiQ_Lc_FdzFIN1ZHCCIy0 enr:-Ku4QOkvvf0u5Hg4-HhY-SJmEyft77G5h3rUM8VF_e-Hag5cAma3jtmFoX4WElLAqdILCA-UWFRN1ZCDJJVuEHrFeLkDh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCo_ujukAAAaf__________gmlkgnY0gmlwhJK-AWeJc2VjcDI1NmsxoQLFcT5VE_NMiIC8Ll7GypWDnQ4UEmuzD7hF_Hf4veDJwIN1ZHCCIy0 enr:-Ku4QH6tYsHKITYeHUu5kdfXgEZWI18EWk_2RtGOn1jBPlx2UlS_uF3Pm5Dx7tnjOvla_zs-wwlPgjnEOcQDWXey51QCh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCo_ujukAAAaf__________gmlkgnY0gmlwhIs7Mc6Jc2VjcDI1NmsxoQIET4Mlv9YzhrYhX_H9D7aWMemUrvki6W4J2Qo0YmFMp4N1ZHCCIy0 enr:-Ku4QDmz-4c1InchGitsgNk4qzorWMiFUoaPJT4G0IiF8r2UaevrekND1o7fdoftNucirj7sFFTTn2-JdC2Ej0p1Mn8Ch2F0dG5ldHOIAAAAAAAAAACEZXRoMpCo_ujukAAAaf__________gmlkgnY0gmlwhKpA-liJc2VjcDI1NmsxoQMpHP5U1DK8O_JQU6FadmWbE42qEdcGlllR8HcSkkfWq4N1ZHCCIy0 enr:-KO4QP7MmB3juk8rUjJHcUoxZDU9Np4FlW0HyDEGIjSO7GD9PbSsabu7713cWSUWKDkxIypIXg1A-6lG7ySRGOMZHeGCAmuEZXRoMpDTH2GRkAAAc___________gmlkgnY0gmlwhBSoyGOJc2VjcDI1NmsxoQNta5b_bexSSwwrGW2Re24MjfMntzFd0f2SAxQtMj3ueYN0Y3CCIyiDdWRwgiMo enr:-KG4QJejf8KVtMeAPWFhN_P0c4efuwu1pZHELTveiXUeim6nKYcYcMIQpGxxdgT2Xp9h-M5pr9gn2NbbwEAtxzu50Y8BgmlkgnY0gmlwhEEVkQCDaXA2kCoBBPnAEJg4AAAAAAAAAAGJc2VjcDI1NmsxoQLEh_eVvk07AQABvLkTGBQTrrIOQkzouMgSBtNHIRUxOIN1ZHCCIyiEdWRwNoIjKA enr:-Iq4QMCTfIMXnow27baRUb35Q8iiFHSIDBJh6hQM5Axohhf4b6Kr_cOCu0htQ5WvVqKvFgY28893DHAg8gnBAXsAVqmGAX53x8JggmlkgnY0gmlwhLKAlv6Jc2VjcDI1NmsxoQK6S-Cii_KmfFdUJL2TANL3ksaKUnNXvTCv1tLwXs0QgIN1ZHCCIyk enr:-L64QC9Hhov4DhQ7mRukTOz4_jHm4DHlGL726NWH4ojH1wFgEwSin_6H95Gs6nW2fktTWbPachHJ6rUFu0iJNgA0SB2CARqHYXR0bmV0c4j__________4RldGgykDb6UBOQAABx__________-CaWSCdjSCaXCEA-2vzolzZWNwMjU2azGhA17lsUg60R776rauYMdrAz383UUgESoaHEzMkvm4K6k6iHN5bmNuZXRzD4N0Y3CCIyiDdWRwgiMo]
self=enr:-Mq4QNjn1H5jh4gCfO4N9GTncWOsFQAp7WaWjlKAVjPZIvlLDTuyJWI5iJ_h0WGrnk_KogSuM3j7NTAzAe7UHXla0GuGAZXYV4Dph2F0dG5ldHOIAAAAAAAAABiEZXRoMpAUBFtakAAAdf__________gmlkgnY0gmlwhMCo8i2EcXVpY4IyyIlzZWNwMjU2azGhAkeN2mOSAJho0T9gO94PrtjIAi29hOmCCFDqilYBehJgiHN5bmNuZXRzAIN0Y3CCMsiDdWRwgi7g,/ip4/192.168.242.45/tcp/13000/p2p/16Uiu2HAkzEzP7jCW9gKww38Pq5MWFMSJMngjEZawvQwgUGW3oa1D,/ip4/192.168.242.45/udp/13000/quic-v1/p2p/16Uiu2HAkzEzP7jCW9gKww38Pq5MWFMSJMngjEZawvQwgUGW3oa1D

0 peers
```

### Has this worked before in a previous version?

```text
No
```

### 🔬 Minimal Reproduction

Upgrade  any prysm-beacon node to v5.3.1 on Ubuntu 22.04

### Error

```text

```

### Platform(s)

Linux (x86)

### What version of Prysm are you running? (Which release)

5.3.1

### Anything else relevant (validator index / public key)?

Nodes needed manual injection of peers to work

**Comment by nalepae** [comment]
Can you past the complete command line used to run the beacon node?

**Comment by abbaahmad** [comment]
> Can you past the complete command line used to run the beacon node?
```
/home/prysm/beacon-chain --accept-terms-of-use --http-port=3500 --http-host=0.0.0.0 --sepolia --checkpoint-sync-url=https://beaconstate-sepolia.chainsafe.io --genesis-beacon-api-url=https://beaconstate-sepolia.chainsafe.io --peer "/ip4/65.108.68.79/tcp/22541/p2p/16Uiu2HAmEXjJidwnTaf3cM59bsLdu9Mqgd1s5jSf5MuDc9Ec9RV3" --peer "/ip4/20.168.200.99/tcp/9000/p2p/16Uiu2HAmL27wdRkTbAjXHLFonJmScMGiHNB9cDwWybVzkX7FQH9r" --peer "/ip4/147.28.185.148/tcp/4001/p2p/16Uiu2HAm45ssD5Tt8RgRNvGP6jK7AeChPP9AhnpbVB6PY8Q8Xzho" --peer "/ip4/38.97.60.3/tcp/22541/p2p/16Uiu2HAkw3G3fE8wfyn6DBDfXengMLGsuL3aBGxdzRdj32ZPJ5dF" --peer "/ip4/65.108.68.79/tcp/22541/p2p/16Uiu2HAmEXjJidwnTaf3cM59bsLdu9Mqgd1s5jSf5MuDc9Ec9RV3,/ip4/20.168.200.99/tcp/9000/p2p/16Uiu2HAmL27wdRkTbAjXHLFonJmScMGiHNB9cDwWybVzkX7FQH9r,/ip4/147.28.185.148/tcp/4001/p2p/16Uiu2HAm45ssD5Tt8RgRNvGP6jK7AeChPP9AhnpbVB6PY8Q8Xzho,/ip4/38.97.60.3/tcp/22541/p2p/16Uiu2HAkw3G3fE8wfyn6DBDfXengMLGsuL3aBGxdzRdj32ZPJ5dF" --min-sync-peers=1 --execution-endpoint=http://192.168.242.47:8551 --jwt-secret=/home/prysm/jwtsecret
```

**Comment by RicoToothless** [comment]
We also faced the same issue on both v5.3.2 and v6.0.0 on Hoodi.

It happened after upgrading or restarting the Prysm

**Comment by nalepae** [comment]
We are working on it for hoodi.

**Comment by james-prysm** [comment]
I believe this was resolved. closing

**Comment by pragmaxim** [comment]
Imho it is not resolved, we at Trezor are facing this issue for a long time on Sepolia testnet, `required=3 suitable=2` ... so either there are only 2-3 of us left or there is something wrong. 

Is there a service that list the live peers for individual networks ?
