### ISSUE TITLE
ssz.TreeHashRoot takes 20s on mainnet config

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/prysm#2993]
Most likely due to very long historicalRoots list (16,777,216)

**Comment by prestonvanloon** [comment]
pprof of TestReceiveBlock_ProcessCorrectly test run with full mainnet config.
[pprof.zip](https://github.com/prysmaticlabs/prysm/files/3429633/pprof.zip)

Total wall time of ssz related methods 75s. Looks like 4 times called. About 17s each.

**Comment by prestonvanloon** [comment]
![Screenshot from 2019-07-24 23-41-39](https://user-images.githubusercontent.com/7246818/61844223-a3d72e00-ae6c-11e9-9d0f-9bdaeb5df9b9.png)

**Comment by rauljordan** [comment]
Resolved by https://github.com/prysmaticlabs/go-ssz/pull/58 mainnet beacon state now takes 500ms max

**Comment by prestonvanloon** [comment]
There is still a TODO for this. I'll submit a PR. https://github.com/prysmaticlabs/prysm/blob/956b07f5c164abb3d364c8e874ee37425143bf00/beacon-chain/blockchain/block_processing_test.go#L31

**Comment by prestonvanloon** [comment]
This is still an issue. One test case is experiencing 60s state tree hash root with that TODO hack removed. 

![Screenshot from 2019-07-29 16-29-24](https://user-images.githubusercontent.com/7246818/62080172-1efa6480-b21e-11e9-8bfb-afccb9fbdd3d.png)


[pprof.zip](https://github.com/prysmaticlabs/prysm/files/3444169/pprof.zip)

This is from commit 68f29967f3473b893f933305984874dff4c0fe44, which includes prysmaticlabs/go-ssz#58 in the WORKSPACE.

```
bazel test //beacon-chain/blockchain:go_default_test --test_arg=-test.v --test_output=streamed --test_filter=TestReceiveBlock_UsesParentBlockState --test_arg=-
test.cpuprofile=/tmp/cpu.profile --test_output=streamed --test_timeout=0,0,0,0
```

**Comment by prestonvanloon** [comment]
The flame graph may be misleading that a single hash takes 20s. But in the test, there is 20s of wall time stuck in the hashing of the state. The only parameters that change are the length of the HistoricalRootsLimit

**Comment by rauljordan** [comment]
<img width="1402" alt="Screen Shot 2019-08-07 at 2 03 40 PM" src="https://user-images.githubusercontent.com/5572669/62654035-94ec8300-b924-11e9-8a97-2c58bd0e0cd6.png">

New flamegraph takes < 4s and only 0.18s are for SSZ

**Comment by prestonvanloon** [comment]
The TODO still exists. I'll submit a PR to remove it. 

https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/blockchain/block_processing_test.go#L31

**Comment by prestonvanloon** [comment]
The isolated `TestReceiveBlock_UsesParentBlockState` still takes over 100 seconds and the flame graph still points to ssz.

![Screenshot from 2019-08-08 02-04-11](https://user-images.githubusercontent.com/7246818/62678978-f93d3000-b980-11e9-9092-acae8e778c89.png)

As long as the TODO exists, this issue should not be marked as closed. The entire target times out after 5 minutes with the hacked config removed.
