### ISSUE TITLE
security issue when creating a key pair by the proposed method on our site

### ISSUE THREAD

**Issue by shayzluf** [prysmaticlabs/prysm#5434]
the terminal command `./prysm.sh validator accounts create --keystore-path=$HOME/validator --password=` is saved in terminal history and can be retrieved easily.

it will be better to advise users to write the command `./prysm.sh validator accounts create --keystore-path=$HOME/validator` and enter those values as inputs

**Comment by prestonvanloon** [comment]
Why close this? I think it's a valid issue.

**Comment by rauljordan** [comment]
Resolved by the PRs above @shayzluf

**Comment by wgknowles** [comment]
Not fully resolved yet...

.\prysm.bat validator accounts keys --keystore-path=..\validator
[2020-05-02 15:35:40] FATAL main: password is required
