### ISSUE TITLE
Fix aggregator to send unaggregated attestation

### ISSUE THREAD

**Issue by terencechain** [prysmaticlabs/prysm#6110]
Prysm has an incorrect assumption that only `aggregated` attestation can flow in `beacon_aggregate_and_proof` subnet. This assumption has blocked attester from submitting its own unaggregated attestation or aggregator from submitting unaggregated attestation in v0.12. Validators will lose money because of this
```
level=error msg="Could not submit slot signature to beacon node: rpc error: code = Internal desc = No aggregated attestation in beacon node" prefix=validator slot=5612
```

**Comment by rauljordan** [comment]
Resolved by #6109

**Comment by terencechain** [comment]
Ah. Not resolved #6109. That fixes the resolver side.
We'll still need to fix the sender side. I'll address this tomorrow

**Comment by rauljordan** [comment]
Got it, sorry @terencechain didn't see the associated issue before closing this. Title could have a been a bit more descriptive as it felt like a duplicate of an old issue
