### ISSUE TITLE
Sudden drop of connected peers

### ISSUE THREAD

**Issue by raphpa** [prysmaticlabs/prysm#6324]
# 🐞 Bug Report

### Description

Peer count suddenly drops to around 5-7 peers and never raises to 30 again.

![image](https://user-images.githubusercontent.com/18283997/85200315-ad744a80-b2f6-11ea-9120-399d7f5fb10e.png)

It is running on a home line with a 24h disconnect where the ip is likely to change after reconnecting. Beacon-node is set to announce the ddns name with `--p2p-host-dns`

- 24h disconnect was around 3:20h that night, but peers started dropping at around 2:00h already
- On previous days the disconnect had only minimal effect and peer count raised to 30 immediately again.
- There are still inbound and outbound connections happening occasionally.

### Has this worked before in a previous version?

Never noticed similar problems.

## 🔬 Minimal Reproduction

Not tried to reproduce it yet.

## 🌍  Your Environment

**Operating System:**

Ubuntu 20.04 on arm64
Docker

**What version of Prysm are you running? (Which release)**

802bdf5 compiled from source

**Comment by raphpa** [comment]
It never got back to 30 peer so far. After forcing the network to reconnect some outbound connections were started until 7 peers were reached.

![image](https://user-images.githubusercontent.com/18283997/85208823-a28bdb00-b333-11ea-988b-36895c31644d.png)

**Comment by metanull-operator** [comment]
Adding my own info here.

![image](https://user-images.githubusercontent.com/54516310/85307599-55138900-b46d-11ea-8e98-d6a47d66d980.png)

Commit: d4545233cd45d28f03e5dccb8929ce807f4468a6

**Comment by raphpa** [comment]
> Adding my own info here.
> 
> ![image](https://user-images.githubusercontent.com/54516310/85307599-55138900-b46d-11ea-8e98-d6a47d66d980.png)
> 
> Commit: [d454523](https://github.com/prysmaticlabs/prysm/commit/d4545233cd45d28f03e5dccb8929ce807f4468a6)

This is actually the normal behavior if you do not change the maximum peer count. It should stay at around 30 peers. Having around 150 peers was a faulty behavior of previous versions.

**Comment by metanull-operator** [comment]
Makes sense. I wondered why default peers were so high in the prior version. I assumed it was just part of that looser peer connection handling I had recently read about.

**Comment by nisdas** [comment]
hey guys this should be resolved with #6346 . Just comment here, if it doesn't work.

**Comment by raphpa** [comment]
This seems to be still happening.
Prysm/v1.0.0-alpha.12/73f3a653bffe0b40e77972fbe58ff783586a69b6. Built at: 2020-06-26 13:04:43+00:00

Starting at around 02:17 in the logs. See [onyx.log](https://github.com/prysmaticlabs/prysm/files/4843949/onyx.log)


![image](https://user-images.githubusercontent.com/18283997/85976252-6bc05f80-b9da-11ea-90a2-719172f62281.png)

**Comment by nisdas** [comment]
@raphpa do you get the same with alpha.13 ?

**Comment by nisdas** [comment]
Nvm I will re-open it

**Comment by raphpa** [comment]
Not yet, but it only showed up after some days of uptime the last times

**Comment by raphpa** [comment]
On the VPS with 2bce9c8 I now have an uptime of around 6 days with no peer drops. 
On the RPi on a landline it was not able to recover after a 20 minute connection loss. The ports are still reachable from the outside, but there seem to be no incoming or outgoing connections.

```
time="2020-07-05 11:48:36" level=debug msg="No peers found subscribed to attestation gossip subnet with committee index 18. Searching network for peers subscribed to the subnet." prefix=sync
time="2020-07-05 11:48:36" level=debug msg="No peers found subscribed to attestation gossip subnet with committee index 36. Searching network for peers subscribed to the subnet." prefix=sync
time="2020-07-05 11:48:36" level=debug msg="No peers found subscribed to attestation gossip subnet with committee index 24. Searching network for peers subscribed to the subnet." prefix=sync
time="2020-07-05 11:48:36" level=debug msg="No peers found subscribed to attestation gossip subnet with committee index 33. Searching network for peers subscribed to the subnet." prefix=sync
```

![onyx2](https://user-images.githubusercontent.com/18283997/86531982-7ab97d00-bec6-11ea-8469-21cd4352ec5a.png)

**Comment by raphpa** [comment]
Not sure if this is related to this issue. Now the altona node on my VPS did not drop peers, but suddenly stopped syncing new blocks. Trace error level was not yet enabled.

```
time="2020-07-09 17:30:53" level=info msg="Starting next epoch" epoch=2297 finalizedEpoch=2294 justifiedEpoch=2295 prefix=blockchain previousJustifiedEpoch=2295
time="2020-07-09 17:30:53" level=info msg="Validator registry information" activeValidators=3227 averageBalance="32.20020 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 17:30:53" level=info msg="Synced new block" block=0xfd4e2374... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73504
time="2020-07-09 17:30:53" level=info msg="Finished applying state transition" attestations=38 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:31:05" level=info msg="Synced new block" block=0xd8ef0c37... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73505
time="2020-07-09 17:31:05" level=info msg="Finished applying state transition" attestations=17 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:31:29" level=info msg="Synced new block" block=0xd0412e07... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73507
time="2020-07-09 17:31:29" level=info msg="Finished applying state transition" attestations=3 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:31:41" level=info msg="Synced new block" block=0xad978382... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73508
time="2020-07-09 17:31:41" level=info msg="Finished applying state transition" attestations=5 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:31:53" level=info msg="Synced new block" block=0x2d6ce74b... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73509
time="2020-07-09 17:31:53" level=info msg="Finished applying state transition" attestations=5 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:32:17" level=info msg="Synced new block" block=0xec3149e2... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73511
time="2020-07-09 17:32:17" level=info msg="Finished applying state transition" attestations=5 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:32:41" level=info msg="Synced new block" block=0x5f487fc9... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73513
time="2020-07-09 17:32:41" level=info msg="Finished applying state transition" attestations=14 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:33:05" level=info msg="Synced new block" block=0x05ca41e0... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73515
time="2020-07-09 17:33:05" level=info msg="Finished applying state transition" attestations=29 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:33:17" level=info msg="Synced new block" block=0x9a33619f... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73516
time="2020-07-09 17:33:17" level=info msg="Finished applying state transition" attestations=9 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:33:29" level=info msg="Synced new block" block=0xb0e94d9a... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73517
time="2020-07-09 17:33:29" level=info msg="Finished applying state transition" attestations=8 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:33:41" level=info msg="Synced new block" block=0x17357c9f... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73518
time="2020-07-09 17:33:41" level=info msg="Finished applying state transition" attestations=5 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:33:53" level=info msg="Synced new block" block=0x50b19f8b... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73519
time="2020-07-09 17:33:53" level=info msg="Finished applying state transition" attestations=5 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:34:05" level=info msg="Synced new block" block=0x22d2f59d... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73520
time="2020-07-09 17:34:05" level=info msg="Finished applying state transition" attestations=1 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:34:17" level=info msg="Synced new block" block=0xd6cfc5f1... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73521
time="2020-07-09 17:34:17" level=info msg="Finished applying state transition" attestations=10 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:34:29" level=info msg="Synced new block" block=0xc95edcae... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73522
time="2020-07-09 17:34:29" level=info msg="Finished applying state transition" attestations=3 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:34:41" level=info msg="Synced new block" block=0xd6dc80e7... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73523
time="2020-07-09 17:34:41" level=info msg="Finished applying state transition" attestations=19 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:34:53" level=info msg="Synced new block" block=0x220e0693... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73524
time="2020-07-09 17:34:53" level=info msg="Finished applying state transition" attestations=7 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:35:05" level=info msg="Synced new block" block=0x2ffcc016... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73525
time="2020-07-09 17:35:05" level=info msg="Finished applying state transition" attestations=4 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:35:17" level=info msg="Synced new block" block=0xe90ff748... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73526
time="2020-07-09 17:35:17" level=info msg="Finished applying state transition" attestations=14 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:35:29" level=info msg="Synced new block" block=0x6140ced5... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73527
time="2020-07-09 17:35:29" level=info msg="Finished applying state transition" attestations=6 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:35:41" level=info msg="Synced new block" block=0xc92f5ba9... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73528
time="2020-07-09 17:35:41" level=info msg="Finished applying state transition" attestations=4 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:35:53" level=info msg="Synced new block" block=0x001cb341... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73529
time="2020-07-09 17:35:53" level=info msg="Finished applying state transition" attestations=6 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:36:19" level=info msg="Synced new block" block=0x2733a5c1... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73531
time="2020-07-09 17:36:19" level=info msg="Finished applying state transition" attestations=34 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:36:29" level=info msg="Synced new block" block=0x7d69d956... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73532
time="2020-07-09 17:36:29" level=info msg="Finished applying state transition" attestations=1 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:36:41" level=info msg="Synced new block" block=0x99614967... epoch=2297 finalizedEpoch=2294 finalizedRoot=0x7462b6ae... prefix=blockchain slot=73533
time="2020-07-09 17:36:41" level=info msg="Finished applying state transition" attestations=14 attesterSlashings=0 deposits=0 prefix=blockchain proposerSlashings=0 voluntaryExits=0
time="2020-07-09 17:37:29" level=info msg="Starting next epoch" epoch=2298 finalizedEpoch=2295 justifiedEpoch=2297 prefix=blockchain previousJustifiedEpoch=2295
time="2020-07-09 17:37:29" level=info msg="Validator registry information" activeValidators=3227 averageBalance="32.20028 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 17:38:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_3/ssz_snappy"
time="2020-07-09 17:43:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_18/ssz_snappy"
time="2020-07-09 17:43:53" level=info msg="Starting next epoch" epoch=2299 finalizedEpoch=2295 justifiedEpoch=2297 prefix=blockchain previousJustifiedEpoch=2297
time="2020-07-09 17:43:53" level=info msg="Validator registry information" activeValidators=3227 averageBalance="32.20037 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 17:43:55" level=error msg="Failed to ping peer" error="stream reset" peer=16Uiu2HAmQ51KbDQE4XM6FbiewjVEmvziQ9gyFNfsqJMemrzE9iv4 prefix=p2p
time="2020-07-09 17:43:55" level=error msg="Failed to ping peer" error="stream reset" peer=16Uiu2HAm6zLWPgcFGe5qR5SW3346iTZCgChM9Aoq2tiefVkxod7Y prefix=p2p
time="2020-07-09 17:43:55" level=error msg="Failed to ping peer" error="stream reset" peer=16Uiu2HAmTkGCa3WmQCiqpBqM6sQ16AmbeQ9qfBupVFGeHeaK6ewg prefix=p2p
time="2020-07-09 17:43:55" level=error msg="Failed to ping peer" error="stream reset" peer=16Uiu2HAmKvyXP7YTcKfyKHfssLVQDKbCSEMSnf6RnAbwynuBmkE5 prefix=p2p
time="2020-07-09 17:43:56" level=error msg="Failed to ping peer" error="stream reset" peer=16Uiu2HAm6WHJXB12SnrncsVJeJZWG6F7yCNXnuPKUCXuiUQ6DUra prefix=p2p
time="2020-07-09 17:44:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_1/ssz_snappy"
time="2020-07-09 17:46:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_11/ssz_snappy"
time="2020-07-09 17:50:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_31/ssz_snappy"
time="2020-07-09 17:50:06" level=info msg="Starting next epoch" epoch=2300 finalizedEpoch=2297 justifiedEpoch=2298 prefix=blockchain previousJustifiedEpoch=2297
time="2020-07-09 17:50:06" level=info msg="Validator registry information" activeValidators=3227 averageBalance="32.20043 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 17:56:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_29/ssz_snappy"
time="2020-07-09 17:56:29" level=info msg="Starting next epoch" epoch=2301 finalizedEpoch=2298 justifiedEpoch=2300 prefix=blockchain previousJustifiedEpoch=2298
time="2020-07-09 17:56:29" level=info msg="Validator registry information" activeValidators=3223 averageBalance="32.20048 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:02:53" level=info msg="Starting next epoch" epoch=2302 finalizedEpoch=2300 justifiedEpoch=2301 prefix=blockchain previousJustifiedEpoch=2300
time="2020-07-09 18:02:53" level=info msg="Validator registry information" activeValidators=3219 averageBalance="32.20054 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:06:43" level=info msg="Peer disconnected" activePeers=30 multiAddr="/ip4/149.224.144.198/tcp/9011/p2p/16Uiu2HAmBwmP6FN6b3FVzXnmL5zyEfZVAvVpWmLw2nDRDgj8xVhY" prefix=p2p
time="2020-07-09 18:08:29" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_27/ssz_snappy"
time="2020-07-09 18:08:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_29/ssz_snappy"
time="2020-07-09 18:09:24" level=error msg="Failed to revalidate peer" error="i/o deadline exceeded" peer=16Uiu2HAm6zLWPgcFGe5qR5SW3346iTZCgChM9Aoq2tiefVkxod7Y prefix=sync
time="2020-07-09 18:09:29" level=info msg="Starting next epoch" epoch=2303 finalizedEpoch=2301 justifiedEpoch=2302 prefix=blockchain previousJustifiedEpoch=2301
time="2020-07-09 18:09:29" level=info msg="Validator registry information" activeValidators=3215 averageBalance="32.20060 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:12:36" level=error msg="Failed to revalidate peer" error="i/o deadline exceeded" peer=16Uiu2HAm6zLWPgcFGe5qR5SW3346iTZCgChM9Aoq2tiefVkxod7Y prefix=sync
time="2020-07-09 18:15:41" level=info msg="Starting next epoch" epoch=2304 finalizedEpoch=2302 justifiedEpoch=2303 prefix=blockchain previousJustifiedEpoch=2302
time="2020-07-09 18:15:41" level=info msg="Validator registry information" activeValidators=3211 averageBalance="32.20066 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:15:48" level=error msg="Failed to revalidate peer" error="i/o deadline exceeded" peer=16Uiu2HAm6zLWPgcFGe5qR5SW3346iTZCgChM9Aoq2tiefVkxod7Y prefix=sync
time="2020-07-09 18:16:29" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_3/ssz_snappy"
time="2020-07-09 18:18:41" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_14/ssz_snappy"
time="2020-07-09 18:19:00" level=error msg="Failed to revalidate peer" error="i/o deadline exceeded" peer=16Uiu2HAm6zLWPgcFGe5qR5SW3346iTZCgChM9Aoq2tiefVkxod7Y prefix=sync
time="2020-07-09 18:22:08" level=error msg="Failed to revalidate peer" error="stream reset" peer=16Uiu2HAm6zLWPgcFGe5qR5SW3346iTZCgChM9Aoq2tiefVkxod7Y prefix=sync
time="2020-07-09 18:22:08" level=info msg="Peer disconnected" activePeers=29 multiAddr="/ip4/149.224.144.198/tcp/59218/p2p/16Uiu2HAm6zLWPgcFGe5qR5SW3346iTZCgChM9Aoq2tiefVkxod7Y" prefix=p2p
time="2020-07-09 18:22:16" level=info msg="Peer connected" activePeers=30 direction=Outbound multiAddr="/ip4/192.252.232.200/tcp/9000/p2p/16Uiu2HAmEWNCABixR4c8YYFgArGpvcCBDRZehiCWD9ZJq5hsJ4pM" prefix=p2p
time="2020-07-09 18:22:17" level=info msg="Peer connected" activePeers=31 direction=Outbound multiAddr="/ip4/136.243.15.46/tcp/13000/p2p/16Uiu2HAm43kCTp6ztBqmkhb1xPqFWkzWvzxbcJxdEBy1hCaMVLZ4" prefix=p2p
time="2020-07-09 18:22:17" level=info msg="Starting next epoch" epoch=2305 finalizedEpoch=2303 justifiedEpoch=2304 prefix=blockchain previousJustifiedEpoch=2303
time="2020-07-09 18:22:17" level=info msg="Validator registry information" activeValidators=3207 averageBalance="32.20072 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:28:30" level=info msg="Starting next epoch" epoch=2306 finalizedEpoch=2304 justifiedEpoch=2305 prefix=blockchain previousJustifiedEpoch=2304
time="2020-07-09 18:28:30" level=info msg="Validator registry information" activeValidators=3203 averageBalance="32.20078 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:32:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_17/ssz_snappy"
time="2020-07-09 18:34:54" level=info msg="Starting next epoch" epoch=2307 finalizedEpoch=2304 justifiedEpoch=2305 prefix=blockchain previousJustifiedEpoch=2305
time="2020-07-09 18:34:54" level=info msg="Validator registry information" activeValidators=3199 averageBalance="32.20085 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:36:29" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_7/ssz_snappy"
time="2020-07-09 18:41:18" level=info msg="Saved state in DB" archivedIndex=36 prefix=state-gen root=ac6f4f4bceff slot=73728
time="2020-07-09 18:41:18" level=info msg="Starting next epoch" epoch=2308 finalizedEpoch=2305 justifiedEpoch=2307 prefix=blockchain previousJustifiedEpoch=2305
time="2020-07-09 18:41:18" level=info msg="Validator registry information" activeValidators=3195 averageBalance="32.20091 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:42:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_7/ssz_snappy"
time="2020-07-09 18:45:29" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_20/ssz_snappy"
time="2020-07-09 18:47:41" level=info msg="Starting next epoch" epoch=2309 finalizedEpoch=2307 justifiedEpoch=2308 prefix=blockchain previousJustifiedEpoch=2307
time="2020-07-09 18:47:41" level=info msg="Validator registry information" activeValidators=3191 averageBalance="32.20097 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:54:06" level=info msg="Starting next epoch" epoch=2310 finalizedEpoch=2308 justifiedEpoch=2309 prefix=blockchain previousJustifiedEpoch=2308
time="2020-07-09 18:54:06" level=info msg="Validator registry information" activeValidators=3187 averageBalance="32.20104 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 18:56:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_9/ssz_snappy"
time="2020-07-09 19:00:29" level=info msg="Starting next epoch" epoch=2311 finalizedEpoch=2309 justifiedEpoch=2310 prefix=blockchain previousJustifiedEpoch=2309
time="2020-07-09 19:00:29" level=info msg="Validator registry information" activeValidators=3183 averageBalance="32.20111 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:06:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_27/ssz_snappy"
time="2020-07-09 19:06:53" level=info msg="Starting next epoch" epoch=2312 finalizedEpoch=2310 justifiedEpoch=2311 prefix=blockchain previousJustifiedEpoch=2310
time="2020-07-09 19:06:53" level=info msg="Validator registry information" activeValidators=3179 averageBalance="32.20118 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:13:17" level=info msg="Starting next epoch" epoch=2313 finalizedEpoch=2311 justifiedEpoch=2312 prefix=blockchain previousJustifiedEpoch=2311
time="2020-07-09 19:13:17" level=info msg="Validator registry information" activeValidators=3175 averageBalance="32.20124 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:19:53" level=info msg="Starting next epoch" epoch=2314 finalizedEpoch=2312 justifiedEpoch=2313 prefix=blockchain previousJustifiedEpoch=2312
time="2020-07-09 19:19:53" level=info msg="Validator registry information" activeValidators=3171 averageBalance="32.20130 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:26:05" level=info msg="Starting next epoch" epoch=2315 finalizedEpoch=2313 justifiedEpoch=2314 prefix=blockchain previousJustifiedEpoch=2313
time="2020-07-09 19:26:05" level=info msg="Validator registry information" activeValidators=3167 averageBalance="32.20137 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:28:29" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_11/ssz_snappy"
time="2020-07-09 19:29:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_18/ssz_snappy"
time="2020-07-09 19:32:30" level=info msg="Starting next epoch" epoch=2316 finalizedEpoch=2314 justifiedEpoch=2315 prefix=blockchain previousJustifiedEpoch=2314
time="2020-07-09 19:32:30" level=info msg="Validator registry information" activeValidators=3163 averageBalance="32.20143 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:38:53" level=info msg="Starting next epoch" epoch=2317 finalizedEpoch=2315 justifiedEpoch=2316 prefix=blockchain previousJustifiedEpoch=2315
time="2020-07-09 19:38:53" level=info msg="Validator registry information" activeValidators=3159 averageBalance="32.20149 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:45:29" level=info msg="Starting next epoch" epoch=2318 finalizedEpoch=2316 justifiedEpoch=2317 prefix=blockchain previousJustifiedEpoch=2316
time="2020-07-09 19:45:29" level=info msg="Validator registry information" activeValidators=3155 averageBalance="32.20156 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:51:53" level=info msg="Starting next epoch" epoch=2319 finalizedEpoch=2317 justifiedEpoch=2318 prefix=blockchain previousJustifiedEpoch=2317
time="2020-07-09 19:51:53" level=info msg="Validator registry information" activeValidators=3151 averageBalance="32.20162 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 19:53:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_10/ssz_snappy"
time="2020-07-09 19:58:17" level=info msg="Starting next epoch" epoch=2320 finalizedEpoch=2317 justifiedEpoch=2318 prefix=blockchain previousJustifiedEpoch=2318
time="2020-07-09 19:58:17" level=info msg="Validator registry information" activeValidators=3147 averageBalance="32.20168 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:02:04" level=info msg="Peer disconnected" activePeers=30 multiAddr="/ip4/35.158.98.17/tcp/13000/p2p/16Uiu2HAmFT7Hc8wYjHbF9mGCwhHHZTbB14DcEaz3fFEcUc4V8iWp" prefix=p2p
time="2020-07-09 20:04:31" level=info msg="Starting next epoch" epoch=2321 finalizedEpoch=2318 justifiedEpoch=2320 prefix=blockchain previousJustifiedEpoch=2318
time="2020-07-09 20:04:31" level=info msg="Validator registry information" activeValidators=3143 averageBalance="32.20174 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:09:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_26/ssz_snappy"
time="2020-07-09 20:11:05" level=info msg="Starting next epoch" epoch=2322 finalizedEpoch=2320 justifiedEpoch=2321 prefix=blockchain previousJustifiedEpoch=2320
time="2020-07-09 20:11:05" level=info msg="Validator registry information" activeValidators=3139 averageBalance="32.20180 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:12:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_9/ssz_snappy"
time="2020-07-09 20:14:26" level=info msg="Peer disconnected" activePeers=29 multiAddr="/ip4/3.121.239.123/tcp/13000/p2p/16Uiu2HAmCuiLgoFzaBzCTUZ1WxrZ5EErPGRHovAaUASSyVCsGaBC" prefix=p2p
time="2020-07-09 20:14:29" level=info msg="Peer connected" activePeers=30 direction=Outbound multiAddr="/ip4/149.224.107.222/tcp/9011/p2p/16Uiu2HAmBwmP6FN6b3FVzXnmL5zyEfZVAvVpWmLw2nDRDgj8xVhY" prefix=p2p
time="2020-07-09 20:17:17" level=info msg="Starting next epoch" epoch=2323 finalizedEpoch=2321 justifiedEpoch=2322 prefix=blockchain previousJustifiedEpoch=2321
time="2020-07-09 20:17:17" level=info msg="Validator registry information" activeValidators=3135 averageBalance="32.20187 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:23:42" level=info msg="Starting next epoch" epoch=2324 finalizedEpoch=2322 justifiedEpoch=2323 prefix=blockchain previousJustifiedEpoch=2322
time="2020-07-09 20:23:42" level=info msg="Validator registry information" activeValidators=3131 averageBalance="32.19775 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:30:05" level=info msg="Starting next epoch" epoch=2325 finalizedEpoch=2323 justifiedEpoch=2324 prefix=blockchain previousJustifiedEpoch=2323
time="2020-07-09 20:30:05" level=info msg="Validator registry information" activeValidators=3127 averageBalance="32.19782 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:36:30" level=info msg="Starting next epoch" epoch=2326 finalizedEpoch=2324 justifiedEpoch=2325 prefix=blockchain previousJustifiedEpoch=2324
time="2020-07-09 20:36:30" level=info msg="Validator registry information" activeValidators=3123 averageBalance="32.19788 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:42:41" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_30/ssz_snappy"
time="2020-07-09 20:42:53" level=info msg="Starting next epoch" epoch=2327 finalizedEpoch=2325 justifiedEpoch=2326 prefix=blockchain previousJustifiedEpoch=2325
time="2020-07-09 20:42:53" level=info msg="Validator registry information" activeValidators=3119 averageBalance="32.19795 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:49:17" level=info msg="Starting next epoch" epoch=2328 finalizedEpoch=2326 justifiedEpoch=2327 prefix=blockchain previousJustifiedEpoch=2326
time="2020-07-09 20:49:17" level=info msg="Validator registry information" activeValidators=3115 averageBalance="32.19801 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 20:55:41" level=info msg="Starting next epoch" epoch=2329 finalizedEpoch=2327 justifiedEpoch=2328 prefix=blockchain previousJustifiedEpoch=2327
time="2020-07-09 20:55:41" level=info msg="Validator registry information" activeValidators=3111 averageBalance="32.19808 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:00:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_21/ssz_snappy"
time="2020-07-09 21:02:05" level=info msg="Starting next epoch" epoch=2330 finalizedEpoch=2328 justifiedEpoch=2329 prefix=blockchain previousJustifiedEpoch=2328
time="2020-07-09 21:02:05" level=info msg="Validator registry information" activeValidators=3107 averageBalance="32.19814 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:08:07" level=info msg="Peer disconnected" activePeers=29 multiAddr="/ip4/93.103.215.225/tcp/9000/p2p/16Uiu2HAkzbaKuu8t2evRdRGWGiYNk9yGK1K8T3shxXJ6w5o63YGG" prefix=p2p
time="2020-07-09 21:08:17" level=info msg="Peer connected" activePeers=30 direction=Outbound multiAddr="/ip4/45.77.48.102/tcp/9000/p2p/16Uiu2HAmLPDjXtPnXzaPUv9LPTvaypV7f3PGduRCmReGCtwVPTXN" prefix=p2p
time="2020-07-09 21:08:30" level=info msg="Starting next epoch" epoch=2331 finalizedEpoch=2329 justifiedEpoch=2330 prefix=blockchain previousJustifiedEpoch=2329
time="2020-07-09 21:08:30" level=info msg="Validator registry information" activeValidators=3103 averageBalance="32.19820 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:11:53" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_16/ssz_snappy"
time="2020-07-09 21:14:53" level=info msg="Starting next epoch" epoch=2332 finalizedEpoch=2330 justifiedEpoch=2331 prefix=blockchain previousJustifiedEpoch=2330
time="2020-07-09 21:14:53" level=info msg="Validator registry information" activeValidators=3099 averageBalance="32.19827 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:21:29" level=info msg="Starting next epoch" epoch=2333 finalizedEpoch=2331 justifiedEpoch=2332 prefix=blockchain previousJustifiedEpoch=2331
time="2020-07-09 21:21:29" level=info msg="Validator registry information" activeValidators=3095 averageBalance="32.19833 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:27:41" level=info msg="Starting next epoch" epoch=2334 finalizedEpoch=2331 justifiedEpoch=2332 prefix=blockchain previousJustifiedEpoch=2332
time="2020-07-09 21:27:41" level=info msg="Validator registry information" activeValidators=3091 averageBalance="32.19839 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:29:54" level=info msg="Peer disconnected" activePeers=29 multiAddr="/ip4/107.137.107.212/tcp/1026/p2p/16Uiu2HAmEhcSXSn1g1qDUGd45v9SM9tDa6KNVzQFAp3tGhiZPjaT" prefix=p2p
time="2020-07-09 21:29:56" level=info msg="Peer connected" activePeers=30 direction=Outbound multiAddr="/ip4/3.121.125.218/tcp/9000/p2p/16Uiu2HAm6FBad3xnXj4WkkjpjaQQedn4rCmh8jCww2uw6MSSFNs2" prefix=p2p
time="2020-07-09 21:34:05" level=info msg="Starting next epoch" epoch=2335 finalizedEpoch=2332 justifiedEpoch=2334 prefix=blockchain previousJustifiedEpoch=2332
time="2020-07-09 21:34:05" level=info msg="Validator registry information" activeValidators=3087 averageBalance="32.19845 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:40:29" level=info msg="Starting next epoch" epoch=2336 finalizedEpoch=2334 justifiedEpoch=2335 prefix=blockchain previousJustifiedEpoch=2334
time="2020-07-09 21:40:29" level=info msg="Validator registry information" activeValidators=3083 averageBalance="32.19850 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:42:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_7/ssz_snappy"
time="2020-07-09 21:46:53" level=info msg="Starting next epoch" epoch=2337 finalizedEpoch=2335 justifiedEpoch=2336 prefix=blockchain previousJustifiedEpoch=2335
time="2020-07-09 21:46:53" level=info msg="Validator registry information" activeValidators=3079 averageBalance="32.19857 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:52:05" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_25/ssz_snappy"
time="2020-07-09 21:53:30" level=info msg="Starting next epoch" epoch=2338 finalizedEpoch=2336 justifiedEpoch=2337 prefix=blockchain previousJustifiedEpoch=2336
time="2020-07-09 21:53:30" level=info msg="Validator registry information" activeValidators=3075 averageBalance="32.19869 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 21:59:42" level=info msg="Starting next epoch" epoch=2339 finalizedEpoch=2337 justifiedEpoch=2338 prefix=blockchain previousJustifiedEpoch=2337
time="2020-07-09 21:59:42" level=info msg="Validator registry information" activeValidators=3071 averageBalance="32.19880 ETH" prefix=blockchain totalValidators=3367
time="2020-07-09 22:02:17" level=warning msg="Subscription next failed" error="subscription cancelled by calling sub.Cancel()" prefix=sync topic="/eth2/fdca39b0/beacon_attestation_12/ssz_snappy"
```

**Comment by rauljordan** [comment]
Hi @farazdagi wondering if you know about this issue or if it is still relevant

**Comment by rauljordan** [comment]
Has not been observed recently in normal network conditions. We also have new peer scoring in place that can help prevent some of this. If anyone still sees this issue in a good network, it is worth an investigation
