### ISSUE TITLE
Prysm Validator Missing Attestations

### ISSUE THREAD

**Issue by ben-staked** [prysmaticlabs/prysm#8066]
# 🐞 Bug Report

### Description

The prysm client occasionally misses attestations for slots due to grpc deadline for making the attestations passing before it's able to make the attestations.  It errors out with `Could not request attestation to sign at slot` when it does this.

As the number of keys that the validator client is attesting for goes up, the probability of this happening also seems to rise, since the deadline is fixed at 12 seconds for retrieving proposals and attestations and the amount of work to do appears to linearly scale with the amount of keys attesting.  Resource usage for the validator and for the beacon chain remain fairly low (compared to the available resources), so it doesn't seem to be a resource starvation issue.

### Has this worked before in a previous version?

This behavior has been observed in previous versions, but it was only recently that it became apparent it was directly related to the number of attesting validators.

## 🔬 Minimal Reproduction

The beacon chain and validator are run separately from each other, with the validator talking to a remote keymanager.

Beacon chain
```
beacon-chain
  --accept-terms-of-use
  --datadir /data
  --rpc-host 0.0.0.0
  --rpc-port 4000
  --grpc-gateway-host 0.0.0.0
  --grpc-gateway-port 4001
  --block-batch-limit=512
  --tls-cert certfile.crt
  --tls-key keyfile.crt
  --http-web3provider=$WEB3_PROVIDER
```

Validator
```
validator 
  --accept-terms-of-use
  --wallet-dir=/home/prysm/
  --beacon-rpc-provider $BEACON_DNS:4000
  --tls-cert certfile.crt
  --verbosity debug
  --wallet-password-file file.txt
```

The validator is also running using a remote keymanager.

## 🔥 Error

<pre><code>
time="2020-12-07 15:57:11" level=debug msg="Set deadline for proposals and attestations" deadline=2020-12-07 15:57:23 +0000 UTC prefix=validator slot=TARGET_SLOT
time="2020-12-07 15:57:13" level=debug msg="gRPC request finished." backend=[] duration=1.864267969s method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties"
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=2 prefix=validator pubKeys=[0xKEY1 0xKEY2] slot=TARGET_SLOT
...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:13" level=info msg="Attestation schedule" attesters=... prefix=validator pubKeys=[...] slot=...
time="2020-12-07 15:57:20" level=debug msg="gRPC request finished." backend=[] duration=88.037671ms method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties"
time="2020-12-07 15:57:20" level=debug msg="gRPC request finished." backend=[] duration=624.1µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/DomainData"
time="2020-12-07 15:57:26" level=debug msg="gRPC request finished." backend=[] duration=895.563µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/SubscribeCommitteeSubnets"
time="2020-12-07 15:57:26" level=debug msg="gRPC request finished." backend=[] duration=38.785µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData"
time="2020-12-07 15:57:26" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xKEY1 slot=TARGET_SLOT
time="2020-12-07 15:57:26" level=debug msg="gRPC request finished." backend=[] duration=42.394µs method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetAttestationData"
time="2020-12-07 15:57:26" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xKEY2 slot=TARGET_SLOT
time="2020-12-07 15:57:26" level=error msg="Could not sign slot: rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
Prysm v1.0.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by tsudmi** [comment]
Also experiencing the same issue in `v1.0.3`.

**Comment by StanleyDing** [comment]
Encountered the same issue in v1.0.3

**Comment by prestonvanloon** [comment]
This may have been fixed by https://github.com/prysmaticlabs/prysm/pull/8023.

Can you confirm two things:
- Did you have a non-zero amount of validators that were not yet active? If so, can you give an approximate number? 10, 100, etc
- Does this issue still exist in v1.0.4? v1.0.4 has PR #8023 included, so that might resolve your issue.

**Comment by ben-staked** [comment]
- There are not very many inactive validators on the node that I'm looking at.  In general, I've observed that active validators contribute more heavily to the bug than inactive ones.
- I will test it out on `v1.0.4` and update

**Comment by prestonvanloon** [comment]
Thanks @ben-staked. I'm also thinking that #8023 might not have resolved your issue, based on the logs provided in the original issue. 

Something seems off about the timestamps in the logs. I understand you've edited out any identifiable information, but did you also remove other logs? I'm specifically looking for this type of log
```
time="2020-12-07 15:57:11" level=debug msg="Set deadline for proposals and attestations" deadline=2020-12-07 15:57:23 +0000 UTC prefix=validator slot=TARGET_SLOT
```
I don't see one in your logs prior to the calls at `2020-12-07 15:57:26`.

I also see a call to GetDuties, but nothing else was logged... i.e. attestation schedule, etc
```
time="2020-12-07 15:57:20" level=debug msg="gRPC request finished." backend=[] duration=88.037671ms method="/ethereum.eth.v1alpha1.BeaconNodeValidator/GetDuties"
```
I would have expected the deadline to update at the start of the new epoch, when the validator had made the call to GetDuties.

**Comment by prestonvanloon** [comment]
Was the previous epoch task so delayed that it ran into the next epoch? 
Another weird thing is that your logs show an epoch deadline of only 1 slot. 
What slot did this happen at?

**Comment by prestonvanloon** [comment]
Ah actually it's a slot deadline... that makes sense, still looking

**Comment by protolambda** [comment]
I think I'm also hitting attestation deadlines on all my Pyrmont validators.
```
time="2020-12-08 22:58:08" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xa37d58e64c33 slot=147289
time="2020-12-08 22:58:08" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xaf7013f5eaf7 slot=147289
time="2020-12-08 22:58:08" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xb5388e4bfaa4 slot=147289
time="2020-12-08 22:58:09" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x88764236d100 slot=147289
time="2020-12-08 22:58:11" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x881962ed46ed slot=147289
time="2020-12-08 22:58:11" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xb359ee01551d slot=147289
time="2020-12-08 22:58:11" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xa7c43e224193 slot=147289
time="2020-12-08 22:58:12" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xa7f14ac9787a slot=147289
time="2020-12-08 22:58:12" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0xb465dd83d368 slot=147289
time="2020-12-08 22:58:13" level=error msg="Could not submit attestation to beacon node" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validator pubKey=0x9718fa44e3bd slot=147289
```
It then requests more, and times out against, same after restarts as after running for a while.

Version: `Prysm/v1.0.4/ade3b2f2dffc242341dfc0793984b431a889e5b2. Built at: 2020-12-08 04:02:32+00:00`

**Comment by prestonvanloon** [comment]
@protolambda if all of your validators are hitting deadlines, that might be a bigger and different issue. 
For some context, we aren't seeing any wide spread deadlines in pyrmont with our validators. 
However, we are seeing a slight increase deadlines exceeded in pyrmont in the last 1 to 2 hours and we are investigating that.

**Comment by protolambda** [comment]
Messaged on telegram chat just now, copying that over:
> Downgrading to v1.0.3 seems to have helped, I see nodes attesting now, not stuck on endless validator GRPC timeouts anymore. Something between those two versions must have made timeouts for stressed BN/VC setups a lot more common.

I definitely think something changed, but not sure what it could be. Just a little extra stress on the nodes, or something related to bad RPC / timeout behavior.

**Comment by StanleyDing** [comment]
> This may have been fixed by #8023.
> 
> Can you confirm two things:
> 
> * Did you have a non-zero amount of validators that were not yet active? If so, can you give an approximate number? 10, 100, etc
> * Does this issue still exist in v1.0.4? v1.0.4 has PR #8023 included, so that might resolve your issue.

Have around 500 inactive validators. We run our validators in a k8s cluster, and it will often fail after running for a couple of hours if using beacon node within the k8s. Currently we are using beacon node outside of k8s cluster, and the validator looks normal now.

**Comment by ben-staked** [comment]
@prestonvanloon It seems like 1.0.4 helped a little bit.  Hitting deadlines still happens, but it's a little bit less frequent than before.  Is there any way to raise the deadline?

**Comment by rauljordan** [comment]
v1.0.5 should resolve these issues completely @ben-staked , can you check if that's the case?

**Comment by ben-staked** [comment]
@rauljordan That didn't seem to help at all.  Still getting the same rate of attestation misses on validators with the same message.

I don't think I was clear about this in my original bug report, but whenever the validator misses, it misses for all attestations in that slot.

**Comment by sriney-staked** [comment]
I want to pile on with another thing, but maybe need to file a separate bug/issue.

When an aggregation (not just attestation) is done with two or more keys, we observe sometimes that the inclusion distance is very high (20+).  Seems to also only happen in bigger > 100 validator wallets.+

**Comment by tsudmi** [comment]
@prestonvanloon , @rauljordan Still getting this in `v1.0.5`:
```
time="2021-01-03 13:49:02" level=info msg="Attestation schedule" attesters="4/169" prefix=validator pubKeys=[0xad26a4e7b98b 0xb422c5d4ee45 0x943931bdb5d9 0x8ec92ab24751] slot=331744
time="2021-01-03 13:49:07" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validato
r pubKey=0xb422c5d4ee45 slot=331744
time="2021-01-03 13:49:07" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validato
r pubKey=0x8ec92ab24751 slot=331744
time="2021-01-03 13:49:07" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validato
r pubKey=0xad26a4e7b98b slot=331744
time="2021-01-03 13:49:07" level=error msg="Could not request attestation to sign at slot" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" prefix=validato
r pubKey=0x943931bdb5d9 slot=331744
```
