### ISSUE TITLE
Empty `slashing_protection.json` after export

### ISSUE THREAD

**Issue by pablomendezroyo** [prysmaticlabs/prysm#9897]
# 🐞 Bug Report

### Description

I have exported in more than 1 prater validator the **slashing protection database** using the CLI. In all cases, the slashing protection database results in a JSON file with empty key values that seems to be wrong, like the following:
```
{
	"metadata": {
		"interchange_format_version": "5",
		"genesis_validators_root": "0x043db0d9a83813551ee2f33450d23797757d430911a9320530ad8a0eabc43efb"
	},
	"data": [
		{
			"pubkey": "0x80b11b83eb8c1858c657dc55936bd4b47d2418c8906777cecae9c14495796f3d52b44652684e25e9ebb3e9efcfea33c6",
			"signed_blocks": [],
			"signed_attestations": []
		}
	]
}
```
### Has this worked before in a previous version?

I have not tried the slashing protection database export before.
## 🔬 Minimal Reproduction
To reproduce the issue just do a normal **export of the validator slashing protection database** with 
```
validator slashing-protection export --datadir=/root/.eth2validators
```
The output logs are
```
validator --prater slashing-protection export --datadir=/root/.eth2validators
[2021-11-12 16:35:02]  WARN flags: Running on the Prater Testnet
[2021-11-12 16:35:02]  INFO slashingprotection: This command exports your validator's attestation and proposal history into a file that can then be imported into any other Prysm setup across computers
Extracting signed blocks by validator public key 100% [================================]  [0s:0s]
Enter your desired output directory for your slashing protection history file:
/root 
[2021-11-12 16:35:13]  INFO slashingprotection: Writing slashing protection export JSON file to /root/slashing_protection.json
[2021-11-12 16:35:13]  INFO slashingprotection: Successfully wrote /root/slashing_protection.json
```

## 🔥 Error
The `slashing_protection.json` JSON file seems to have something wrong, especially the following empty key-values
<pre><code>

"signed_blocks": [],
"signed_attestations": []
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Docker container running on a Debian host
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
v2.0.2
  </code>
</pre>

**Anything else relevant (validator index / public key)?**
The validator was executed with the following flags
```
validator \
  --prater \
  --datadir=/root/.eth2 \
  --rpc-host 0.0.0.0 \
  --monitoring-host 0.0.0.0 \
  --beacon-rpc-provider=\"$BEACON_RPC_PROVIDER\" \
  --beacon-rpc-gateway-provider=\"$BEACON_RPC_GATEWAY_PROVIDER\" \
  --wallet-dir=/root/.eth2validators \
  --wallet-password-file=/root/.eth2wallets/wallet-password.txt \
  --write-wallet-password-on-web-onboarding \
  --graffiti=\"$GRAFFITI\" \
  --web \
  --grpc-gateway-host=0.0.0.0 \
  --grpc-gateway-port=80 \
  --accept-terms-of-use
```

**Comment by dapplion** [comment]
Note that this validator is actively attesting https://prater.beaconcha.in/validator/80b11b83eb8c1858c657dc55936bd4b47d2418c8906777cecae9c14495796f3d52b44652684e25e9ebb3e9efcfea33c6#attestations

So the slashing protection data should be populated

**Comment by rauljordan** [comment]
Hi @dapplion and @pablomendezroyo I believe the issue is because you are doing
```
validator --prater slashing-protection export --datadir=/root/.eth2validators
```
but your validator datadir is set to `/root/.eth2` from

```
validator \
  --prater \
  --datadir=/root/.eth2 \
  --rpc-host 0.0.0.0 \
```
Can you try changing it to the .eth2 directory instead in the first command? We know this is super confusing, but hard for us to change and unify the walletdir and datadir at this point without dangerous, breaking changes to users. Instead, we're thinking of adding warnings in case the slashing protection history is empty and letting them know some common issues. In this case, the validator slashing protection is placed in the datadir.

**Comment by rauljordan** [comment]
I'll open a PR that adds warning messages here which should resolve this problem from happening to others

**Comment by pablomendezroyo** [comment]
hey, thank you for the response.  I am still getting thef ollowing error
```
[2021-11-15 21:24:19] FATAL Could not export slashing protection file: validator.db file (validator database) was not found at path /root/.eth2, so nothing to export
```

I have used the `--datadir /root/.eth2validators` because the `validator.db` is at `/root/.eth2validators` as the following shows
```
# pwd
/root/.eth2validators
# ls -la
total 52
drwx------ 3 root root     4096 Nov 12 16:27 .
drwx------ 5 root root     4096 Nov 15 21:22 ..
-rw------- 1 root root      150 Nov 12 08:53 auth-token
drwx------ 3 root root     4096 Oct 13 06:46 direct
-rw------- 1 root root       60 Oct  7 09:25 rpc-password-hash
-rw------- 1 root root        0 Nov 12 16:27 tosaccepted
-rw------- 1 root root 16809984 Nov 15 21:22 validator.db
-rw------- 1 root root        9 Oct  7 09:25 walletpassword.txt
```

**Comment by pablomendezroyo** [comment]
The issue should be re-opened since the slashing-protection data is empty in the `validator.db` as well

According to @rauljordan the Issue could be related to running `validator` with `--web` flag
